[package]
name = "backend"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.3.2"
actix-web-actors = "3.0.0"
actix-files = "0.3"
actix = "0.10.0"
env_logger = "0.6.0"
rand = "0.8.4"